# Generated by Django 6.0.2 on 2026-03-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('web', 'Web'), ('app', 'App'), ('ai', 'AI')], max_length=20)),
                ('option_type', models.CharField(choices=[('base', 'Base'), ('extra', 'Extra')], max_length=10)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BuilderPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('websites', 'Websites'), ('apps', 'Apps'), ('ai', 'AI')], max_length=50)),
                ('subcategory', models.CharField(choices=[('ready-made', 'Ready Made'), ('custom', 'Custom'), ('apps', 'Apps'), ('ai', 'AI')], max_length=50)),
                ('tier', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('billing_one_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('features', models.JSONField(default=list)),
                ('popular', models.BooleanField(default=False)),
                ('best_value', models.BooleanField(default=False)),
                ('footnote', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
