from .account_views import (
    ChangeEmailView,
    ChangePasswordView,
    LoginHistoryView,
    MeView,
    SecurityEventsView,
    UserProfileView,
)
from .admin_views import (
    AdminOnlyView,
    AdminUsersListView,
    RestoreUserView,
    SuspendUserView,
    ToggleUserStatusView,
    UserDetailView,
    UserListCreateView,
    UserListView,
)
from .auth_views import (
    CustomTokenObtainPairView,
    CustomTokenRefreshView,
    ForgotPasswordView,
    LoginView,
    LogoutView,
    RegisterView,
    ResendVerificationEmailView,
    ResetPasswordView,
    Setup2FAView,
    Verify2FAView,
    Verify2FALoginView,
    VerifyEmailView,
)
from .session_views import DeviceSessionsView, RevokeDeviceSessionView, UserSessionsView


__all__ = [
    "AdminOnlyView",
    "AdminUsersListView",
    "ChangeEmailView",
    "ChangePasswordView",
    "CustomTokenObtainPairView",
    "CustomTokenRefreshView",
    "DeviceSessionsView",
    "ForgotPasswordView",
    "LoginHistoryView",
    "LoginView",
    "LogoutView",
    "MeView",
    "RegisterView",
    "ResendVerificationEmailView",
    "ResetPasswordView",
    "RestoreUserView",
    "RevokeDeviceSessionView",
    "SecurityEventsView",
    "Setup2FAView",
    "SuspendUserView",
    "ToggleUserStatusView",
    "UserDetailView",
    "UserListCreateView",
    "UserListView",
    "UserProfileView",
    "UserSessionsView",
    "Verify2FAView",
    "Verify2FALoginView",
    "VerifyEmailView",
]
