# Generated by Django 6.0.2 on 2026-03-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_securityalert_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('failed_logins', models.IntegerField(default=0)),
                ('request_count', models.IntegerField(default=0)),
                ('last_request', models.DateTimeField(auto_now=True)),
                ('risk_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('failed_logins', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(default=0)),
                ('request_count', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
