# Generated by Django 6.0.2 on 2026-03-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_ipactivity_suspiciousip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockedip',
            old_name='expires_at',
            new_name='blocked_until',
        ),
        migrations.RemoveField(
            model_name='blockedip',
            name='reason',
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
