# Generated by Django 6.0.2 on 2026-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_harden_security_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
            ],
        ),
    ]
