# Generated by Django 6.0.2 on 2026-03-24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0011_trustedip"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustedip",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trustedip",
            name="note",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
