# Generated by Django 6.0.2 on 2026-03-26 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('category', models.JSONField(verbose_name=False)),
                ('type', models.CharField(choices=[('ready', 'Ready-Made'), ('custom', 'Customizable')], max_length=10)),
                ('preview_url', models.URLField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='templates/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_note', models.CharField(blank=True, max_length=255)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('badge_class', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('icons', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
