# Generated by Django 6.0.2 on 2026-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/files/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.JSONField(default=list),
        ),
    ]
