# Generated by Django 6.0.2 on 2026-03-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppService',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.JSONField()),
                ('icon', models.CharField(max_length=100)),
                ('meta', models.JSONField(default=list)),
                ('features', models.JSONField(default=list)),
                ('category', models.CharField(choices=[('service', 'Service'), ('blueprint', 'Blueprint')], max_length=20)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
