# Generated by Django 6.0.2 on 2026-03-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='messages_ap_thread__55ba0e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'is_read', 'sender_role'], name='messages_ap_thread__899eb7_idx'),
        ),
    ]
