# Generated by Django 6.0.2 on 2026-03-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_failedloginattempt_loginattempt_securityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('MODERATOR', 'Moderator')], default='USER', max_length=20),
        ),
    ]
