# Generated by Django 6.0.2 on 2026-03-18 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_devicesession_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_section', to=settings.AUTH_USER_MODEL),
        ),
    ]
