# Generated by Django 6.0.2 on 2026-04-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_enterprise_event_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_team',
            field=models.CharField(blank=True, choices=[('DESIGN', 'Design'), ('DEVELOPMENT', 'Development'), ('QA', 'Quality Assurance'), ('DEVOPS', 'DevOps'), ('PROJECT', 'Project Management'), ('PRODUCT', 'Product'), ('CONTENT', 'Content'), ('OPERATIONS', 'Operations'), ('OTHER', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
