# Generated by Django 6.0.2 on 2026-04-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_staff_team_user_staff_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='date_format',
            field=models.CharField(blank=True, default='MM/DD/YYYY', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='login_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=64),
        ),
    ]
