# Generated by Django 6.0.2 on 2026-03-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('features', models.JSONField(default=list)),
                ('integration', models.JSONField(default=list)),
                ('use_cases', models.JSONField(default=list)),
                ('benefits', models.JSONField(default=list)),
                ('price_note', models.CharField(max_length=255)),
                ('delivery_time', models.CharField(max_length=100)),
                ('preview_url', models.URLField(blank=True)),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('items', models.JSONField(default=list)),
                ('features', models.JSONField(default=list)),
                ('ideal_for', models.JSONField(default=list)),
                ('price_note', models.CharField(max_length=255)),
                ('delivery_time', models.CharField(max_length=100)),
                ('preview_url', models.URLField(blank=True)),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
