# Generated by Django 6.0.2 on 2026-04-01 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0001_initial'),
        ('orders', '0001_initial'),
        ('support', '0002_supportticket_assigned_to_supportticket_escalated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('team', models.CharField(blank=True, choices=[('DESIGN', 'Design'), ('DEVELOPMENT', 'Development'), ('QA', 'Quality Assurance'), ('DEVOPS', 'DevOps'), ('PROJECT', 'Project Management'), ('PRODUCT', 'Product'), ('CONTENT', 'Content'), ('OPERATIONS', 'Operations'), ('OTHER', 'Other')], db_index=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('blocked', 'Blocked'), ('done', 'Done')], db_index=True, default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff_tasks', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='inquiries.inquiry')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='orders.order')),
                ('support_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='support.supportticket')),
            ],
            options={
                'ordering': ['is_deleted', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffTaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('status', 'Status Changed'), ('progress', 'Progress Changed'), ('note', 'Note Added')], default='updated', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_task_activities', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workforce.stafftask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stafftask',
            index=models.Index(fields=['team', 'status'], name='workforce_s_team_9eb9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftask',
            index=models.Index(fields=['assigned_to', 'status'], name='workforce_s_assigne_f4a808_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftask',
            index=models.Index(fields=['priority', 'due_at'], name='workforce_s_priorit_2dd531_idx'),
        ),
    ]
