# Generated by Django 6.0.2 on 2026-03-26 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='review_notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='review_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
