# Generated by Django 6.0.2 on 2026-03-27 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_projectfile_review_notes_projectfile_review_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='review_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], db_index=True, default='pending_review', max_length=20),
        ),
    ]
